# Generated by Django 5.1 on 2024-08-24 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_buyer_email_alter_buyer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potato',
            name='id',
            field=models.CharField(default=uuid.UUID('fc4816bb-87c3-4bd0-9395-b1c77693af2e'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
