# Generated by Django 5.1 on 2024-08-25 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_potato_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='buyer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='username',
        ),
        migrations.AlterField(
            model_name='potato',
            name='id',
            field=models.CharField(default=uuid.UUID('4309902c-0bda-4bdf-9410-50732beaf5d8'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
