# Generated by Django 5.1 on 2024-08-25 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_buyer_managers_remove_buyer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potato',
            name='id',
            field=models.CharField(default=uuid.UUID('79875bc2-bc43-4127-96b9-d2f1036fe1cc'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
