# Generated by Django 5.1 on 2024-08-25 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_potato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potato',
            name='id',
            field=models.CharField(default=uuid.UUID('744ac69c-fb1f-4a37-ae61-b3dd0b4ace44'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
