# Generated by Django 5.1 on 2024-09-01 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_potato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potato',
            name='id',
            field=models.CharField(default=uuid.UUID('2b6977d0-2a9e-4d8b-8fe3-df4abf864cd5'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
