# Generated by Django 5.1 on 2024-09-16 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_potato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potato',
            name='id',
            field=models.CharField(default=uuid.UUID('54dfdf69-efaf-4d5f-81b6-3f7710dfd982'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
