# Generated by Django 5.1.1 on 2024-10-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_assign_trainer_role', 'Can assign trainer role'), ('can_assign_masseur_role', 'Can assign masseur role')]},
        ),
    ]
