# Generated by Django 5.1.1 on 2024-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_assign_trainer_role', 'Может назначить роль Тренера'), ('can_assign_masseur_role', 'Может назначить роль Массажиста'), ('can_assign_admin_role', 'Может назначить роль Администратора')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('visitor', 'Посетитель'), ('trainer', 'Тренер'), ('masseur', 'Массажист'), ('admin', 'Администратор'), ('manager', 'Управляющий')], default='visitor', max_length=10),
        ),
    ]
