# Generated by Django 5.1.1 on 2024-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user_role', 'Может изменять роль пользователя')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('visitor', 'Посетитель'), ('trainer', 'Тренер'), ('masseur', 'Массажист'), ('admin', 'Администратор'), ('manager', 'Управляющий')], default='visitor', max_length=20),
        ),
    ]
