# Generated by Django 5.1.1 on 2024-10-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rolegroupmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.DeleteModel(
            name='RoleGroupMapping',
        ),
    ]
