# Generated by Django 5.1.1 on 2024-10-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_birth_date_customuser_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
