# Generated by Django 5.1.1 on 2024-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='in_gym',
            field=models.BooleanField(default=False),
        ),
    ]
